### ISSUE TITLE
Time Between Scene Capture

### ISSUE THREAD

**Issue by imdoublecats** [NVIDIA/Dataset_Synthesizer#16]
I used the SceneCapture_Simple actor and set the Time Between Scene Capture = 2.0, then it waited for 2 seconds and started capturing. But it kept capturing the rest of the images without any 2 seconds delay between two images, just one frame after another.
So how to solve this problem?

**Comment by thangt** [comment]
This is a bug in the code. I will push a fix for this.
In the mean time, you can manually change the code yourself if you want to:
1. Go to file: ```Dataset_Synthesizer\Source\Plugins\NVSceneCapturer\Source\NVSceneCapturer\Private\NVSceneCapturerActor.cpp```
2. Go to line 371, it should be: ```LastCaptureTimestamp = CurrentTime;```
3. Add new code line after line 371 and before the "}": ```bNeedToExportScene = false;```
4. Compile the solution.

I will notify you when I push the fixes. After the fix is in you can just sync to it and don't need to keep this local change.

**Comment by imdoublecats** [comment]
Thank you, it works.
