### ISSUE TITLE
How can i Randomly Rotate the New data model(made in fbx format) in UE4 for DOPE using NDDS

### ISSUE THREAD

**Issue by avinashsen707** [NVIDIA/Dataset_Synthesizer#49]
I am currently doing a Master Project on Bin Picking of 3D objects, using an Aubo collaborative Robot.
Currently i am trying Nvidia-DOPE library for Object Detection and Pose Esimation for custom domains. I make use of UE4 Engine for data set generation.

can you share your approach that done in; that the 3d model created can randomly rotated in 3d inside the workspace.
i loaded my 3d model inside UE4 , but failed to give random 360 movement for the model that is done in blender(fbx format).

**Comment by avinashsen707** [comment]
The Problem is solved!

You can do it directly by selecting "orbital movement " in NVSCeneCapture Plug in Camera in NDDS.

The orbital movement will be available in double clicking the camera window.
Thank you!

**Comment by ShrutheeshIR** [comment]
Hello
I'm trying to do something similar. I was not able to find 'orbital movement'. Could you please help me out? By giving step by step instructions?
 I am very new to UE4, and hence cannot find my way around it easily. 
If you could provide instructions with screenshots it would be very helpful, otherwise a detailed step by step procedure would also do. Thanks!
