### ISSUE TITLE
Delay between spawning new actors

### ISSUE THREAD

**Issue by KatharinaSchmidt** [NVIDIA/Dataset_Synthesizer#65]
Hey, 
I want to synthesize datatests with objects lying randomly on the floor. 
The object shall also lie on top of each other, so i want them to appear at a random position in my TriggerVolume and fall down. When all object lie on the floor, the captured data shall be saved. 

For now, I am using a GroupActorManager for my objects (works well, diffrent objects appear in the defined volume in diffrent rotations) and a SceneCapturer_Simple with a SceneManager_BP to save the data. 
My problem: a new group of actors spawn in a very short time frame, so the objects can't fall on the floor

I already tried to vary the Spawn Duration, but that doesn't help. 

Can you please tell me what I'm doing wrong? Do I need another actor or component?

Thanks in advance :)

**Comment by smitheric95** [comment]
Based off your description of the problem, `Spawn Duration` should be the correct parameter.

Do you have any images you can share?

**Comment by KatharinaSchmidt** [comment]
Here is a screenshot of the GroupActorManager:
![Group_TrainingObjects](https://user-images.githubusercontent.com/62353042/78813517-6a7c2980-79cd-11ea-848a-dbff2474e677.png)

and a screenshot of the SceneCapturer_Simple: 
![SceneCapturer_Simple](https://user-images.githubusercontent.com/62353042/78813655-a2836c80-79cd-11ea-9038-4b7e6d427efe.png)

Please let me know, which other images are helpful for a solution.

**Comment by KatharinaSchmidt** [comment]
Even if I set Spawn Duration to 0, a new group of actors spawns every frame. 
But the discription says: "If Spawn Duration <= 0 then we only spawn the actors once" 

I appreciate every approach solving this problem.

**Comment by mrkcass** [comment]
A couple things come to mind. 

Eric is correct in that the spawn duration controls the time between respawning. I can verify that this works  though I do not know if I have ever set it to zero. We use group actors on every level, with varying spawn durations and I haven't seen this problem.

Here's some other things to check:
* What are the physics properties of your actors? 
* is physics enabled ?
* is gravity enabled ?
* does the actor have a random movement component? If so, is the teleport option enabled? What is the speed, range of movement and time between movement settings. Is movement relative to object origin.
* have any of the project or world setting for the gravity constant been modified ?
* is your group actor positioned inside or outside your trigger volume?
* does your actor have a random visibility component? If so what is the duration setting?
* what version the plugin are you using? Prior to the commit for issue #16, the delay between capture only affected the first frame. If you have the new version you will see a delay of a hard coded 5 seconds before any frames are collected.
* does the scene appear to freeze periodically which may cause dropped frames? This is caused by many factors in the scene and/or the amount of randomization,  complexity per actor.

**Comment by KatharinaSchmidt** [comment]
Thanks for the help, mrkcass. 
First I created new blueprints for my actors, there I enabled physics and gravity. 
Since i placed the group actor inside my trigger volume it works.
